<?php
/**
 * @file
 * glazed_content_elements_examples_1.features.menu_links.inc
 */

/**
 * Implements hook_menu_default_menu_links().
 */
function glazed_content_elements_examples_1_menu_default_menu_links() {
  $menu_links = array();

  // Exported menu link: main-menu_blockquote:uuid/node/229435b1-1c29-4eab-a591-9c8ceaaff8a0.
  $menu_links['main-menu_blockquote:uuid/node/229435b1-1c29-4eab-a591-9c8ceaaff8a0'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/229435b1-1c29-4eab-a591-9c8ceaaff8a0',
    'router_path' => 'uuid',
    'link_title' => 'Blockquote',
    'options' => array(
      'identifier' => 'main-menu_blockquote:uuid/node/229435b1-1c29-4eab-a591-9c8ceaaff8a0',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -43,
    'customized' => 1,
    'uuid' => '229435b1-1c29-4eab-a591-9c8ceaaff8a0',
    'vuuid' => '98339a5e-8ff1-4108-9b31-bfc020a6b05d',
    'parent_identifier' => 'main-menu_content-elements:<nolink>',
  );
  // Exported menu link: main-menu_buttons:uuid/node/34d13068-3849-4eaf-89d4-880954ac8bdb.
  $menu_links['main-menu_buttons:uuid/node/34d13068-3849-4eaf-89d4-880954ac8bdb'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/34d13068-3849-4eaf-89d4-880954ac8bdb',
    'router_path' => 'uuid',
    'link_title' => 'Buttons',
    'options' => array(
      'identifier' => 'main-menu_buttons:uuid/node/34d13068-3849-4eaf-89d4-880954ac8bdb',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -44,
    'customized' => 1,
    'uuid' => '34d13068-3849-4eaf-89d4-880954ac8bdb',
    'vuuid' => '814f3adb-7e9e-4797-8a82-cde19119a4f2',
    'parent_identifier' => 'main-menu_content-elements:<nolink>',
  );
  // Exported menu link: main-menu_carousel-element:uuid/node/cef1e560-174e-4387-b0a9-82c592ff8ed4.
  $menu_links['main-menu_carousel-element:uuid/node/cef1e560-174e-4387-b0a9-82c592ff8ed4'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/cef1e560-174e-4387-b0a9-82c592ff8ed4',
    'router_path' => 'uuid',
    'link_title' => 'Carousel Element',
    'options' => array(
      'identifier' => 'main-menu_carousel-element:uuid/node/cef1e560-174e-4387-b0a9-82c592ff8ed4',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -50,
    'customized' => 1,
    'uuid' => 'cef1e560-174e-4387-b0a9-82c592ff8ed4',
    'vuuid' => '865e6651-d609-45b9-b78b-f188cda5af16',
    'parent_identifier' => 'main-menu_layout-elements:<nolink>',
  );
  // Exported menu link: main-menu_collapsibles:uuid/node/5b9b97a8-bb26-4288-a08e-5c4891a1fe99.
  $menu_links['main-menu_collapsibles:uuid/node/5b9b97a8-bb26-4288-a08e-5c4891a1fe99'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/5b9b97a8-bb26-4288-a08e-5c4891a1fe99',
    'router_path' => 'uuid',
    'link_title' => 'Collapsibles',
    'options' => array(
      'identifier' => 'main-menu_collapsibles:uuid/node/5b9b97a8-bb26-4288-a08e-5c4891a1fe99',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -47,
    'customized' => 1,
    'uuid' => '5b9b97a8-bb26-4288-a08e-5c4891a1fe99',
    'vuuid' => 'bfc969f2-4ce5-4b0e-919f-61ccd31ea090',
    'parent_identifier' => 'main-menu_content-elements:<nolink>',
  );
  // Exported menu link: main-menu_colored-icon-boxes:uuid/node/4e840855-52c9-47a4-9f74-80fb2734dd92.
  $menu_links['main-menu_colored-icon-boxes:uuid/node/4e840855-52c9-47a4-9f74-80fb2734dd92'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/4e840855-52c9-47a4-9f74-80fb2734dd92',
    'router_path' => 'uuid',
    'link_title' => 'Colored Icon Boxes',
    'options' => array(
      'identifier' => 'main-menu_colored-icon-boxes:uuid/node/4e840855-52c9-47a4-9f74-80fb2734dd92',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -46,
    'customized' => 1,
    'uuid' => '4e840855-52c9-47a4-9f74-80fb2734dd92',
    'vuuid' => '38c4451d-4572-4742-ae86-189eb2f1d210',
    'parent_identifier' => 'main-menu_content-elements:<nolink>',
  );
  // Exported menu link: main-menu_columns:uuid/node/c3b6b1cf-1ae1-48ad-ab3a-0287775fe14a.
  $menu_links['main-menu_columns:uuid/node/c3b6b1cf-1ae1-48ad-ab3a-0287775fe14a'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/c3b6b1cf-1ae1-48ad-ab3a-0287775fe14a',
    'router_path' => 'uuid',
    'link_title' => 'Columns',
    'options' => array(
      'identifier' => 'main-menu_columns:uuid/node/c3b6b1cf-1ae1-48ad-ab3a-0287775fe14a',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -47,
    'customized' => 1,
    'uuid' => 'c3b6b1cf-1ae1-48ad-ab3a-0287775fe14a',
    'vuuid' => '9016c5b6-0100-4da9-af57-1d1c7cdf8fb7',
    'parent_identifier' => 'main-menu_layout-elements:<nolink>',
  );
  // Exported menu link: main-menu_content-elements:<nolink>.
  $menu_links['main-menu_content-elements:<nolink>'] = array(
    'menu_name' => 'main-menu',
    'link_path' => '<nolink>',
    'router_path' => '<nolink>',
    'link_title' => 'Content Elements',
    'options' => array(
      'attributes' => array(
        'title' => '',
      ),
      'identifier' => 'main-menu_content-elements:<nolink>',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 1,
    'expanded' => 1,
    'weight' => -49,
    'customized' => 1,
    'parent_identifier' => 'main-menu_elements:<nolink>',
  );
  // Exported menu link: main-menu_divider:uuid/node/0825174b-b312-41f9-b2f6-64d4c22edefd.
  $menu_links['main-menu_divider:uuid/node/0825174b-b312-41f9-b2f6-64d4c22edefd'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/0825174b-b312-41f9-b2f6-64d4c22edefd',
    'router_path' => 'uuid',
    'link_title' => 'Divider',
    'options' => array(
      'identifier' => 'main-menu_divider:uuid/node/0825174b-b312-41f9-b2f6-64d4c22edefd',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -42,
    'customized' => 1,
    'uuid' => '0825174b-b312-41f9-b2f6-64d4c22edefd',
    'vuuid' => '55ba84bd-dd68-4ab3-a9d9-2d859ccde31c',
    'parent_identifier' => 'main-menu_content-elements:<nolink>',
  );
  // Exported menu link: main-menu_elements:<nolink>.
  $menu_links['main-menu_elements:<nolink>'] = array(
    'menu_name' => 'main-menu',
    'link_path' => '<nolink>',
    'router_path' => '<nolink>',
    'link_title' => 'Elements',
    'options' => array(
      'identifier' => 'main-menu_elements:<nolink>',
      'attributes' => array(
        'title' => '',
      ),
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 1,
    'expanded' => 1,
    'weight' => -49,
    'customized' => 1,
  );
  // Exported menu link: main-menu_gridstack-view:uuid/node/06f8b908-96a6-4fb1-a7a6-d443b8ed2f1b.
  $menu_links['main-menu_gridstack-view:uuid/node/06f8b908-96a6-4fb1-a7a6-d443b8ed2f1b'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/06f8b908-96a6-4fb1-a7a6-d443b8ed2f1b',
    'router_path' => 'uuid',
    'link_title' => 'GridStack View',
    'options' => array(
      'attributes' => array(
        'title' => '',
      ),
      'identifier' => 'main-menu_gridstack-view:uuid/node/06f8b908-96a6-4fb1-a7a6-d443b8ed2f1b',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -49,
    'customized' => 1,
    'uuid' => '06f8b908-96a6-4fb1-a7a6-d443b8ed2f1b',
    'vuuid' => '058a83ba-8d7e-4060-a850-edc363de45c0',
    'parent_identifier' => 'main-menu_content-elements:<nolink>',
  );
  // Exported menu link: main-menu_icon-box:uuid/node/8cee9fbf-2933-45e5-9c12-b6aab9075cfb.
  $menu_links['main-menu_icon-box:uuid/node/8cee9fbf-2933-45e5-9c12-b6aab9075cfb'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/8cee9fbf-2933-45e5-9c12-b6aab9075cfb',
    'router_path' => 'uuid',
    'link_title' => 'Icon Box',
    'options' => array(
      'identifier' => 'main-menu_icon-box:uuid/node/8cee9fbf-2933-45e5-9c12-b6aab9075cfb',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -50,
    'customized' => 1,
    'uuid' => '8cee9fbf-2933-45e5-9c12-b6aab9075cfb',
    'vuuid' => 'a9ce957f-246b-4390-b721-3d1461218f45',
    'parent_identifier' => 'main-menu_content-elements:<nolink>',
  );
  // Exported menu link: main-menu_icon-well:uuid/node/5ff84c19-e9e1-4760-9253-abbedce064cd.
  $menu_links['main-menu_icon-well:uuid/node/5ff84c19-e9e1-4760-9253-abbedce064cd'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/5ff84c19-e9e1-4760-9253-abbedce064cd',
    'router_path' => 'uuid',
    'link_title' => 'Icon Well',
    'options' => array(
      'identifier' => 'main-menu_icon-well:uuid/node/5ff84c19-e9e1-4760-9253-abbedce064cd',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -45,
    'customized' => 1,
    'uuid' => '5ff84c19-e9e1-4760-9253-abbedce064cd',
    'vuuid' => 'dc27f04e-2cc5-418d-962c-2cc3e80a7e9a',
    'parent_identifier' => 'main-menu_content-elements:<nolink>',
  );
  // Exported menu link: main-menu_jumbotron:uuid/node/bfb6a4e5-3557-489b-b949-872f6dd0ebb2.
  $menu_links['main-menu_jumbotron:uuid/node/bfb6a4e5-3557-489b-b949-872f6dd0ebb2'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/bfb6a4e5-3557-489b-b949-872f6dd0ebb2',
    'router_path' => 'uuid',
    'link_title' => 'Jumbotron',
    'options' => array(
      'identifier' => 'main-menu_jumbotron:uuid/node/bfb6a4e5-3557-489b-b949-872f6dd0ebb2',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -44,
    'customized' => 1,
    'uuid' => 'bfb6a4e5-3557-489b-b949-872f6dd0ebb2',
    'vuuid' => '18b9b6fb-85cb-4363-9bfc-858e579310b5',
    'parent_identifier' => 'main-menu_layout-elements:<nolink>',
  );
  // Exported menu link: main-menu_layout-elements:<nolink>.
  $menu_links['main-menu_layout-elements:<nolink>'] = array(
    'menu_name' => 'main-menu',
    'link_path' => '<nolink>',
    'router_path' => '<nolink>',
    'link_title' => 'Layout Elements',
    'options' => array(
      'attributes' => array(
        'title' => '',
      ),
      'identifier' => 'main-menu_layout-elements:<nolink>',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 1,
    'expanded' => 1,
    'weight' => -50,
    'customized' => 1,
    'parent_identifier' => 'main-menu_elements:<nolink>',
  );
  // Exported menu link: main-menu_lead:uuid/node/9e0ff233-9546-4277-bac0-a2e6cb36c8a7.
  $menu_links['main-menu_lead:uuid/node/9e0ff233-9546-4277-bac0-a2e6cb36c8a7'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/9e0ff233-9546-4277-bac0-a2e6cb36c8a7',
    'router_path' => 'uuid',
    'link_title' => 'Lead',
    'options' => array(
      'identifier' => 'main-menu_lead:uuid/node/9e0ff233-9546-4277-bac0-a2e6cb36c8a7',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -42,
    'customized' => 1,
    'uuid' => '9e0ff233-9546-4277-bac0-a2e6cb36c8a7',
    'vuuid' => 'b2dc8315-d563-4a0f-9446-50e0d48382c6',
    'parent_identifier' => 'main-menu_layout-elements:<nolink>',
  );
  // Exported menu link: main-menu_panel:uuid/node/2e6d0201-12ac-40ce-8c42-15b8251b7902.
  $menu_links['main-menu_panel:uuid/node/2e6d0201-12ac-40ce-8c42-15b8251b7902'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/2e6d0201-12ac-40ce-8c42-15b8251b7902',
    'router_path' => 'uuid',
    'link_title' => 'Panel',
    'options' => array(
      'identifier' => 'main-menu_panel:uuid/node/2e6d0201-12ac-40ce-8c42-15b8251b7902',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -45,
    'customized' => 1,
    'uuid' => '2e6d0201-12ac-40ce-8c42-15b8251b7902',
    'vuuid' => '713127eb-ddec-4a30-ac85-3df71dcf06f5',
    'parent_identifier' => 'main-menu_layout-elements:<nolink>',
  );
  // Exported menu link: main-menu_positioned-layers:uuid/node/a5fc2ec5-7d47-40cb-98c3-50916154e18e.
  $menu_links['main-menu_positioned-layers:uuid/node/a5fc2ec5-7d47-40cb-98c3-50916154e18e'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/a5fc2ec5-7d47-40cb-98c3-50916154e18e',
    'router_path' => 'uuid',
    'link_title' => 'Positioned Layers',
    'options' => array(
      'identifier' => 'main-menu_positioned-layers:uuid/node/a5fc2ec5-7d47-40cb-98c3-50916154e18e',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -49,
    'customized' => 1,
    'uuid' => 'a5fc2ec5-7d47-40cb-98c3-50916154e18e',
    'vuuid' => '981c7cb8-fd95-4e9d-87f1-e640d4033cf2',
    'parent_identifier' => 'main-menu_layout-elements:<nolink>',
  );
  // Exported menu link: main-menu_sections-and-backgrounds:uuid/node/969e7879-63f5-464c-a8af-6fb131a1aeed.
  $menu_links['main-menu_sections-and-backgrounds:uuid/node/969e7879-63f5-464c-a8af-6fb131a1aeed'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/969e7879-63f5-464c-a8af-6fb131a1aeed',
    'router_path' => 'uuid',
    'link_title' => 'Sections and Backgrounds',
    'options' => array(
      'identifier' => 'main-menu_sections-and-backgrounds:uuid/node/969e7879-63f5-464c-a8af-6fb131a1aeed',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -48,
    'customized' => 1,
    'uuid' => '969e7879-63f5-464c-a8af-6fb131a1aeed',
    'vuuid' => '5bb59bc1-6081-4892-b8b3-7889aaee2d22',
    'parent_identifier' => 'main-menu_layout-elements:<nolink>',
  );
  // Exported menu link: main-menu_tabs:uuid/node/92e308f2-1208-4b67-ba2b-04dbe2d5833a.
  $menu_links['main-menu_tabs:uuid/node/92e308f2-1208-4b67-ba2b-04dbe2d5833a'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/92e308f2-1208-4b67-ba2b-04dbe2d5833a',
    'router_path' => 'uuid',
    'link_title' => 'Tabs',
    'options' => array(
      'identifier' => 'main-menu_tabs:uuid/node/92e308f2-1208-4b67-ba2b-04dbe2d5833a',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -48,
    'customized' => 1,
    'uuid' => '92e308f2-1208-4b67-ba2b-04dbe2d5833a',
    'vuuid' => '550d3529-e530-42a8-b02d-cb57cea17b8b',
    'parent_identifier' => 'main-menu_content-elements:<nolink>',
  );
  // Exported menu link: main-menu_time-line:uuid/node/b50ca955-ea53-4854-a408-6f39a7262093.
  $menu_links['main-menu_time-line:uuid/node/b50ca955-ea53-4854-a408-6f39a7262093'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/b50ca955-ea53-4854-a408-6f39a7262093',
    'router_path' => 'uuid',
    'link_title' => 'Time Line',
    'options' => array(
      'identifier' => 'main-menu_time-line:uuid/node/b50ca955-ea53-4854-a408-6f39a7262093',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -46,
    'customized' => 1,
    'uuid' => 'b50ca955-ea53-4854-a408-6f39a7262093',
    'vuuid' => 'd481cdb3-14d1-482b-b22e-3080313c1e14',
    'parent_identifier' => 'main-menu_layout-elements:<nolink>',
  );
  // Exported menu link: main-menu_well:uuid/node/ca2e52f4-ec41-4a6b-ae81-6aeef8149192.
  $menu_links['main-menu_well:uuid/node/ca2e52f4-ec41-4a6b-ae81-6aeef8149192'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/ca2e52f4-ec41-4a6b-ae81-6aeef8149192',
    'router_path' => 'uuid',
    'link_title' => 'Well',
    'options' => array(
      'identifier' => 'main-menu_well:uuid/node/ca2e52f4-ec41-4a6b-ae81-6aeef8149192',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -43,
    'customized' => 1,
    'uuid' => 'ca2e52f4-ec41-4a6b-ae81-6aeef8149192',
    'vuuid' => '8920a705-c876-4134-8719-9761a2ae9da2',
    'parent_identifier' => 'main-menu_layout-elements:<nolink>',
  );

  // Translatables
  // Included for use with string extractors like potx.
  t('Blockquote');
  t('Buttons');
  t('Carousel Element');
  t('Collapsibles');
  t('Colored Icon Boxes');
  t('Columns');
  t('Content Elements');
  t('Divider');
  t('Elements');
  t('GridStack View');
  t('Icon Box');
  t('Icon Well');
  t('Jumbotron');
  t('Layout Elements');
  t('Lead');
  t('Panel');
  t('Positioned Layers');
  t('Sections and Backgrounds');
  t('Tabs');
  t('Time Line');
  t('Well');

  return $menu_links;
}
