<?php
/**
 * @file
 * glazed_canvas_theme_settings.features.menu_links.inc
 */

/**
 * Implements hook_menu_default_menu_links().
 */
function glazed_canvas_theme_settings_menu_default_menu_links() {
  $menu_links = array();

  // Exported menu link: main-menu_about-me:uuid/node/09c313be-63ee-4325-a474-12ea5c8792db.
  $menu_links['main-menu_about-me:uuid/node/09c313be-63ee-4325-a474-12ea5c8792db'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/09c313be-63ee-4325-a474-12ea5c8792db',
    'router_path' => 'uuid',
    'link_title' => 'About Me',
    'options' => array(
      'identifier' => 'main-menu_about-me:uuid/node/09c313be-63ee-4325-a474-12ea5c8792db',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -50,
    'customized' => 1,
    'uuid' => '09c313be-63ee-4325-a474-12ea5c8792db',
    'vuuid' => '6c88474d-41b9-43c8-bde4-8d93e05b8436',
    'parent_identifier' => 'main-menu_pages:uuid/node/5810252c-ebbb-42e3-9523-fbedc419dc4e',
  );
  // Exported menu link: main-menu_about-us-timeline:uuid/node/fefb9dcc-281b-4544-b7e0-4dfaa4ebf495.
  $menu_links['main-menu_about-us-timeline:uuid/node/fefb9dcc-281b-4544-b7e0-4dfaa4ebf495'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/fefb9dcc-281b-4544-b7e0-4dfaa4ebf495',
    'router_path' => 'uuid',
    'link_title' => 'About Us Timeline',
    'options' => array(
      'identifier' => 'main-menu_about-us-timeline:uuid/node/fefb9dcc-281b-4544-b7e0-4dfaa4ebf495',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -48,
    'customized' => 1,
    'uuid' => 'fefb9dcc-281b-4544-b7e0-4dfaa4ebf495',
    'vuuid' => 'c843d996-8399-4d15-a2a9-3d44f774b8bb',
    'parent_identifier' => 'main-menu_pages:uuid/node/5810252c-ebbb-42e3-9523-fbedc419dc4e',
  );
  // Exported menu link: main-menu_about-us:uuid/node/984cfc78-e4cc-4262-9452-20b267bd3776.
  $menu_links['main-menu_about-us:uuid/node/984cfc78-e4cc-4262-9452-20b267bd3776'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/984cfc78-e4cc-4262-9452-20b267bd3776',
    'router_path' => 'uuid',
    'link_title' => 'About Us',
    'options' => array(
      'identifier' => 'main-menu_about-us:uuid/node/984cfc78-e4cc-4262-9452-20b267bd3776',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -49,
    'customized' => 1,
    'uuid' => '984cfc78-e4cc-4262-9452-20b267bd3776',
    'vuuid' => '4ea452e0-576f-4bfe-91ba-31bc590390c3',
    'parent_identifier' => 'main-menu_pages:uuid/node/5810252c-ebbb-42e3-9523-fbedc419dc4e',
  );
  // Exported menu link: main-menu_animation-engine:uuid/node/34998698-bc3b-4056-a6b6-b793443a2edc.
  $menu_links['main-menu_animation-engine:uuid/node/34998698-bc3b-4056-a6b6-b793443a2edc'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/34998698-bc3b-4056-a6b6-b793443a2edc',
    'router_path' => 'uuid',
    'link_title' => 'Animation Engine',
    'options' => array(
      'identifier' => 'main-menu_animation-engine:uuid/node/34998698-bc3b-4056-a6b6-b793443a2edc',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -50,
    'customized' => 1,
    'uuid' => '34998698-bc3b-4056-a6b6-b793443a2edc',
    'vuuid' => '7e957fae-9b2f-42d1-a3ce-7fe56df0861c',
    'parent_identifier' => 'main-menu_interactive-elements:<nolink>',
  );
  // Exported menu link: main-menu_blockquote:uuid/node/229435b1-1c29-4eab-a591-9c8ceaaff8a0.
  $menu_links['main-menu_blockquote:uuid/node/229435b1-1c29-4eab-a591-9c8ceaaff8a0'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/229435b1-1c29-4eab-a591-9c8ceaaff8a0',
    'router_path' => 'uuid',
    'link_title' => 'Blockquote',
    'options' => array(
      'identifier' => 'main-menu_blockquote:uuid/node/229435b1-1c29-4eab-a591-9c8ceaaff8a0',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -43,
    'customized' => 1,
    'uuid' => '229435b1-1c29-4eab-a591-9c8ceaaff8a0',
    'vuuid' => 'd8e1d96e-5a41-4dda-918d-c47d1f5835aa',
    'parent_identifier' => 'main-menu_content-elements:<nolink>',
  );
  // Exported menu link: main-menu_blog-classic-style:blog.
  $menu_links['main-menu_blog-classic-style:blog'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'blog',
    'router_path' => 'blog',
    'link_title' => 'Blog Classic Style',
    'options' => array(
      'identifier' => 'main-menu_blog-classic-style:blog',
    ),
    'module' => 'system',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -50,
    'customized' => 1,
    'parent_identifier' => 'main-menu_blog:blog',
  );
  // Exported menu link: main-menu_blog-grid-2-columns:blog/grid2.
  $menu_links['main-menu_blog-grid-2-columns:blog/grid2'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'blog/grid2',
    'router_path' => 'blog/grid2',
    'link_title' => 'Blog Grid 2 Columns',
    'options' => array(
      'identifier' => 'main-menu_blog-grid-2-columns:blog/grid2',
    ),
    'module' => 'system',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -48,
    'customized' => 1,
    'parent_identifier' => 'main-menu_blog:blog',
  );
  // Exported menu link: main-menu_blog-grid-3-columns:blog/grid3.
  $menu_links['main-menu_blog-grid-3-columns:blog/grid3'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'blog/grid3',
    'router_path' => 'blog/grid3',
    'link_title' => 'Blog Grid 3 Columns',
    'options' => array(
      'identifier' => 'main-menu_blog-grid-3-columns:blog/grid3',
    ),
    'module' => 'system',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -47,
    'customized' => 1,
    'parent_identifier' => 'main-menu_blog:blog',
  );
  // Exported menu link: main-menu_blog-grid-4-columns:blog/grid4.
  $menu_links['main-menu_blog-grid-4-columns:blog/grid4'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'blog/grid4',
    'router_path' => 'blog/grid4',
    'link_title' => 'Blog Grid 4 Columns',
    'options' => array(
      'identifier' => 'main-menu_blog-grid-4-columns:blog/grid4',
    ),
    'module' => 'system',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -46,
    'customized' => 1,
    'parent_identifier' => 'main-menu_blog:blog',
  );
  // Exported menu link: main-menu_blog-modern-style:blog/modern.
  $menu_links['main-menu_blog-modern-style:blog/modern'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'blog/modern',
    'router_path' => 'blog/modern',
    'link_title' => 'Blog Modern Style',
    'options' => array(
      'identifier' => 'main-menu_blog-modern-style:blog/modern',
    ),
    'module' => 'system',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -49,
    'customized' => 1,
    'parent_identifier' => 'main-menu_blog:blog',
  );
  // Exported menu link: main-menu_blog:blog.
  $menu_links['main-menu_blog:blog'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'blog',
    'router_path' => 'blog',
    'link_title' => 'Blog',
    'options' => array(
      'attributes' => array(
        'title' => '',
      ),
      'identifier' => 'main-menu_blog:blog',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 1,
    'expanded' => 1,
    'weight' => -48,
    'customized' => 1,
  );
  // Exported menu link: main-menu_buttons:uuid/node/34d13068-3849-4eaf-89d4-880954ac8bdb.
  $menu_links['main-menu_buttons:uuid/node/34d13068-3849-4eaf-89d4-880954ac8bdb'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/34d13068-3849-4eaf-89d4-880954ac8bdb',
    'router_path' => 'uuid',
    'link_title' => 'Buttons',
    'options' => array(
      'identifier' => 'main-menu_buttons:uuid/node/34d13068-3849-4eaf-89d4-880954ac8bdb',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -44,
    'customized' => 1,
    'uuid' => '34d13068-3849-4eaf-89d4-880954ac8bdb',
    'vuuid' => 'f8ac5729-684b-4761-b75f-61917d76478b',
    'parent_identifier' => 'main-menu_content-elements:<nolink>',
  );
  // Exported menu link: main-menu_call-to-action:uuid/node/a13b4055-cfd9-4437-9127-35acd06cf9ea.
  $menu_links['main-menu_call-to-action:uuid/node/a13b4055-cfd9-4437-9127-35acd06cf9ea'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/a13b4055-cfd9-4437-9127-35acd06cf9ea',
    'router_path' => 'uuid',
    'link_title' => 'Call to Action',
    'options' => array(
      'identifier' => 'main-menu_call-to-action:uuid/node/a13b4055-cfd9-4437-9127-35acd06cf9ea',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -46,
    'customized' => 1,
    'uuid' => 'a13b4055-cfd9-4437-9127-35acd06cf9ea',
    'vuuid' => '1d2a829e-c546-4c45-804c-6b6ae43698ac',
    'parent_identifier' => 'main-menu_media-elements:<nolink>',
  );
  // Exported menu link: main-menu_carousel-element:uuid/node/cef1e560-174e-4387-b0a9-82c592ff8ed4.
  $menu_links['main-menu_carousel-element:uuid/node/cef1e560-174e-4387-b0a9-82c592ff8ed4'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/cef1e560-174e-4387-b0a9-82c592ff8ed4',
    'router_path' => 'uuid',
    'link_title' => 'Carousel Element',
    'options' => array(
      'identifier' => 'main-menu_carousel-element:uuid/node/cef1e560-174e-4387-b0a9-82c592ff8ed4',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -50,
    'customized' => 1,
    'uuid' => 'cef1e560-174e-4387-b0a9-82c592ff8ed4',
    'vuuid' => 'dccc1d57-3962-401d-8706-b9863033a939',
    'parent_identifier' => 'main-menu_layout-elements:<nolink>',
  );
  // Exported menu link: main-menu_circle-counter:uuid/node/5c9b6810-6a1f-4109-9a8b-2560f5c65d0f.
  $menu_links['main-menu_circle-counter:uuid/node/5c9b6810-6a1f-4109-9a8b-2560f5c65d0f'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/5c9b6810-6a1f-4109-9a8b-2560f5c65d0f',
    'router_path' => 'uuid',
    'link_title' => 'Circle Counter',
    'options' => array(
      'identifier' => 'main-menu_circle-counter:uuid/node/5c9b6810-6a1f-4109-9a8b-2560f5c65d0f',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -47,
    'customized' => 1,
    'uuid' => '5c9b6810-6a1f-4109-9a8b-2560f5c65d0f',
    'vuuid' => 'd1a3426b-d688-47e9-8771-84dddeb0fc71',
    'parent_identifier' => 'main-menu_interactive-elements:<nolink>',
  );
  // Exported menu link: main-menu_collapsibles:uuid/node/5b9b97a8-bb26-4288-a08e-5c4891a1fe99.
  $menu_links['main-menu_collapsibles:uuid/node/5b9b97a8-bb26-4288-a08e-5c4891a1fe99'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/5b9b97a8-bb26-4288-a08e-5c4891a1fe99',
    'router_path' => 'uuid',
    'link_title' => 'Collapsibles',
    'options' => array(
      'identifier' => 'main-menu_collapsibles:uuid/node/5b9b97a8-bb26-4288-a08e-5c4891a1fe99',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -47,
    'customized' => 1,
    'uuid' => '5b9b97a8-bb26-4288-a08e-5c4891a1fe99',
    'vuuid' => 'cf9667fc-1301-40d9-94c6-0f41c23183e1',
    'parent_identifier' => 'main-menu_content-elements:<nolink>',
  );
  // Exported menu link: main-menu_colored-icon-boxes:uuid/node/4e840855-52c9-47a4-9f74-80fb2734dd92.
  $menu_links['main-menu_colored-icon-boxes:uuid/node/4e840855-52c9-47a4-9f74-80fb2734dd92'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/4e840855-52c9-47a4-9f74-80fb2734dd92',
    'router_path' => 'uuid',
    'link_title' => 'Colored Icon Boxes',
    'options' => array(
      'identifier' => 'main-menu_colored-icon-boxes:uuid/node/4e840855-52c9-47a4-9f74-80fb2734dd92',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -46,
    'customized' => 1,
    'uuid' => '4e840855-52c9-47a4-9f74-80fb2734dd92',
    'vuuid' => '6c4d302a-b227-4fc6-9ccd-e836e8770cb0',
    'parent_identifier' => 'main-menu_content-elements:<nolink>',
  );
  // Exported menu link: main-menu_columns:uuid/node/c3b6b1cf-1ae1-48ad-ab3a-0287775fe14a.
  $menu_links['main-menu_columns:uuid/node/c3b6b1cf-1ae1-48ad-ab3a-0287775fe14a'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/c3b6b1cf-1ae1-48ad-ab3a-0287775fe14a',
    'router_path' => 'uuid',
    'link_title' => 'Columns',
    'options' => array(
      'identifier' => 'main-menu_columns:uuid/node/c3b6b1cf-1ae1-48ad-ab3a-0287775fe14a',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -47,
    'customized' => 1,
    'uuid' => 'c3b6b1cf-1ae1-48ad-ab3a-0287775fe14a',
    'vuuid' => '0b333784-0718-4b92-843a-16d910cbe325',
    'parent_identifier' => 'main-menu_layout-elements:<nolink>',
  );
  // Exported menu link: main-menu_contact:contact.
  $menu_links['main-menu_contact:contact'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'contact',
    'router_path' => 'contact',
    'link_title' => 'Contact',
    'options' => array(
      'attributes' => array(
        'title' => '',
      ),
      'identifier' => 'main-menu_contact:contact',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -40,
    'customized' => 1,
    'parent_identifier' => 'main-menu_pages:uuid/node/5810252c-ebbb-42e3-9523-fbedc419dc4e',
  );
  // Exported menu link: main-menu_content-elements:<nolink>.
  $menu_links['main-menu_content-elements:<nolink>'] = array(
    'menu_name' => 'main-menu',
    'link_path' => '<nolink>',
    'router_path' => '<nolink>',
    'link_title' => 'Content Elements',
    'options' => array(
      'attributes' => array(
        'title' => '',
      ),
      'identifier' => 'main-menu_content-elements:<nolink>',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 1,
    'expanded' => 1,
    'weight' => -49,
    'customized' => 1,
    'parent_identifier' => 'main-menu_elements:<nolink>',
  );
  // Exported menu link: main-menu_count-down-timer:uuid/node/9e718e9f-d297-46a8-a908-142b3853d829.
  $menu_links['main-menu_count-down-timer:uuid/node/9e718e9f-d297-46a8-a908-142b3853d829'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/9e718e9f-d297-46a8-a908-142b3853d829',
    'router_path' => 'uuid',
    'link_title' => 'Count Down Timer',
    'options' => array(
      'identifier' => 'main-menu_count-down-timer:uuid/node/9e718e9f-d297-46a8-a908-142b3853d829',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -48,
    'customized' => 1,
    'uuid' => '9e718e9f-d297-46a8-a908-142b3853d829',
    'vuuid' => 'a4a155fe-fcdb-4960-9d62-c7829e3166df',
    'parent_identifier' => 'main-menu_interactive-elements:<nolink>',
  );
  // Exported menu link: main-menu_counter:uuid/node/9c1a0b9b-a4c6-4c74-b134-975d2f0c0f33.
  $menu_links['main-menu_counter:uuid/node/9c1a0b9b-a4c6-4c74-b134-975d2f0c0f33'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/9c1a0b9b-a4c6-4c74-b134-975d2f0c0f33',
    'router_path' => 'uuid',
    'link_title' => 'Counter',
    'options' => array(
      'identifier' => 'main-menu_counter:uuid/node/9c1a0b9b-a4c6-4c74-b134-975d2f0c0f33',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -42,
    'customized' => 1,
    'uuid' => '9c1a0b9b-a4c6-4c74-b134-975d2f0c0f33',
    'vuuid' => '9a1fbcd0-3024-416a-85cc-ffa6fb6ca359',
    'parent_identifier' => 'main-menu_interactive-elements:<nolink>',
  );
  // Exported menu link: main-menu_divider:uuid/node/0825174b-b312-41f9-b2f6-64d4c22edefd.
  $menu_links['main-menu_divider:uuid/node/0825174b-b312-41f9-b2f6-64d4c22edefd'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/0825174b-b312-41f9-b2f6-64d4c22edefd',
    'router_path' => 'uuid',
    'link_title' => 'Divider',
    'options' => array(
      'identifier' => 'main-menu_divider:uuid/node/0825174b-b312-41f9-b2f6-64d4c22edefd',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -42,
    'customized' => 1,
    'uuid' => '0825174b-b312-41f9-b2f6-64d4c22edefd',
    'vuuid' => '68788684-87ac-46e2-8385-99d695c52cab',
    'parent_identifier' => 'main-menu_content-elements:<nolink>',
  );
  // Exported menu link: main-menu_drop-shadow:uuid/node/88d22be5-b9e3-4953-b98b-9c2deac33640.
  $menu_links['main-menu_drop-shadow:uuid/node/88d22be5-b9e3-4953-b98b-9c2deac33640'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/88d22be5-b9e3-4953-b98b-9c2deac33640',
    'router_path' => 'uuid',
    'link_title' => 'Drop Shadow',
    'options' => array(
      'identifier' => 'main-menu_drop-shadow:uuid/node/88d22be5-b9e3-4953-b98b-9c2deac33640',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -44,
    'customized' => 1,
    'uuid' => '88d22be5-b9e3-4953-b98b-9c2deac33640',
    'vuuid' => '5b9edd81-b233-4091-a34a-0d60396bf24f',
    'parent_identifier' => 'main-menu_media-elements:<nolink>',
  );
  // Exported menu link: main-menu_drupal-blocks:uuid/node/621b040c-215e-4302-a133-ee52589bf8c4.
  $menu_links['main-menu_drupal-blocks:uuid/node/621b040c-215e-4302-a133-ee52589bf8c4'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/621b040c-215e-4302-a133-ee52589bf8c4',
    'router_path' => 'uuid',
    'link_title' => 'Drupal Blocks',
    'options' => array(
      'identifier' => 'main-menu_drupal-blocks:uuid/node/621b040c-215e-4302-a133-ee52589bf8c4',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -46,
    'customized' => 1,
    'uuid' => '621b040c-215e-4302-a133-ee52589bf8c4',
    'vuuid' => '254b117a-c4d8-418c-b382-e145d1d4fc45',
    'parent_identifier' => 'main-menu_interactive-elements:<nolink>',
  );
  // Exported menu link: main-menu_drupal-views:uuid/node/8a6234be-e970-4c98-8074-daeda9957d3d.
  $menu_links['main-menu_drupal-views:uuid/node/8a6234be-e970-4c98-8074-daeda9957d3d'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/8a6234be-e970-4c98-8074-daeda9957d3d',
    'router_path' => 'uuid',
    'link_title' => 'Drupal Views',
    'options' => array(
      'identifier' => 'main-menu_drupal-views:uuid/node/8a6234be-e970-4c98-8074-daeda9957d3d',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -45,
    'customized' => 1,
    'uuid' => '8a6234be-e970-4c98-8074-daeda9957d3d',
    'vuuid' => '8d58a593-0012-43a3-a9d1-372c689dcd05',
    'parent_identifier' => 'main-menu_interactive-elements:<nolink>',
  );
  // Exported menu link: main-menu_elements:<nolink>.
  $menu_links['main-menu_elements:<nolink>'] = array(
    'menu_name' => 'main-menu',
    'link_path' => '<nolink>',
    'router_path' => '<nolink>',
    'link_title' => 'Elements',
    'options' => array(
      'identifier' => 'main-menu_elements:<nolink>',
      'attributes' => array(
        'title' => '',
      ),
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 1,
    'expanded' => 1,
    'weight' => -49,
    'customized' => 1,
  );
  // Exported menu link: main-menu_events:events.
  $menu_links['main-menu_events:events'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'events',
    'router_path' => 'events',
    'link_title' => 'Events',
    'options' => array(
      'identifier' => 'main-menu_events:events',
    ),
    'module' => 'system',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -45,
    'customized' => 1,
  );
  // Exported menu link: main-menu_faq:uuid/node/973e2a11-c838-4666-a29c-49487ee8c79f.
  $menu_links['main-menu_faq:uuid/node/973e2a11-c838-4666-a29c-49487ee8c79f'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/973e2a11-c838-4666-a29c-49487ee8c79f',
    'router_path' => 'uuid',
    'link_title' => 'FAQ',
    'options' => array(
      'identifier' => 'main-menu_faq:uuid/node/973e2a11-c838-4666-a29c-49487ee8c79f',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -47,
    'customized' => 1,
    'uuid' => '973e2a11-c838-4666-a29c-49487ee8c79f',
    'vuuid' => 'b3502f2e-e9a3-4a0b-830d-d488b6c31bc4',
    'parent_identifier' => 'main-menu_pages:uuid/node/5810252c-ebbb-42e3-9523-fbedc419dc4e',
  );
  // Exported menu link: main-menu_glazed-filter-no-spacing:portfolio/filter1.
  $menu_links['main-menu_glazed-filter-no-spacing:portfolio/filter1'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'portfolio/filter1',
    'router_path' => 'portfolio/filter1',
    'link_title' => 'Glazed Filter No Spacing',
    'options' => array(
      'identifier' => 'main-menu_glazed-filter-no-spacing:portfolio/filter1',
    ),
    'module' => 'system',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -49,
    'customized' => 1,
    'parent_identifier' => 'main-menu_premium-portfolio:<nolink>',
  );
  // Exported menu link: main-menu_glazed-filter-with-spacing:portfolio/filter2.
  $menu_links['main-menu_glazed-filter-with-spacing:portfolio/filter2'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'portfolio/filter2',
    'router_path' => 'portfolio/filter2',
    'link_title' => 'Glazed Filter With Spacing',
    'options' => array(
      'identifier' => 'main-menu_glazed-filter-with-spacing:portfolio/filter2',
    ),
    'module' => 'system',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -50,
    'customized' => 1,
    'parent_identifier' => 'main-menu_premium-portfolio:<nolink>',
  );
  // Exported menu link: main-menu_glazed-full-screen-modal-portfolio:portfolio/modal2.
  $menu_links['main-menu_glazed-full-screen-modal-portfolio:portfolio/modal2'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'portfolio/modal2',
    'router_path' => 'portfolio/modal2',
    'link_title' => 'Glazed Full Screen Modal Portfolio',
    'options' => array(
      'identifier' => 'main-menu_glazed-full-screen-modal-portfolio:portfolio/modal2',
    ),
    'module' => 'system',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -47,
    'customized' => 1,
    'parent_identifier' => 'main-menu_premium-portfolio:<nolink>',
  );
  // Exported menu link: main-menu_glazed-inline-modal-portfolio:portfolio/modal1.
  $menu_links['main-menu_glazed-inline-modal-portfolio:portfolio/modal1'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'portfolio/modal1',
    'router_path' => 'portfolio/modal1',
    'link_title' => 'Glazed Inline Modal Portfolio',
    'options' => array(
      'identifier' => 'main-menu_glazed-inline-modal-portfolio:portfolio/modal1',
    ),
    'module' => 'system',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -48,
    'customized' => 1,
    'parent_identifier' => 'main-menu_premium-portfolio:<nolink>',
  );
  // Exported menu link: main-menu_glazed-lightbox-portfolio:portfolio/lightbox.
  $menu_links['main-menu_glazed-lightbox-portfolio:portfolio/lightbox'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'portfolio/lightbox',
    'router_path' => 'portfolio/lightbox',
    'link_title' => 'Glazed Lightbox Portfolio',
    'options' => array(
      'identifier' => 'main-menu_glazed-lightbox-portfolio:portfolio/lightbox',
    ),
    'module' => 'system',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -46,
    'customized' => 1,
    'parent_identifier' => 'main-menu_premium-portfolio:<nolink>',
  );
  // Exported menu link: main-menu_google-maps:uuid/node/a4608e7f-a620-4b47-b9a6-3e960302cf32.
  $menu_links['main-menu_google-maps:uuid/node/a4608e7f-a620-4b47-b9a6-3e960302cf32'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/a4608e7f-a620-4b47-b9a6-3e960302cf32',
    'router_path' => 'uuid',
    'link_title' => 'Google Maps',
    'options' => array(
      'identifier' => 'main-menu_google-maps:uuid/node/a4608e7f-a620-4b47-b9a6-3e960302cf32',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -49,
    'customized' => 1,
    'uuid' => 'a4608e7f-a620-4b47-b9a6-3e960302cf32',
    'vuuid' => '046250d5-9faf-4453-87c4-a8f34b5e23fc',
    'parent_identifier' => 'main-menu_media-elements:<nolink>',
  );
  // Exported menu link: main-menu_grid-portfolio:<nolink>.
  $menu_links['main-menu_grid-portfolio:<nolink>'] = array(
    'menu_name' => 'main-menu',
    'link_path' => '<nolink>',
    'router_path' => '<nolink>',
    'link_title' => 'Grid Portfolio',
    'options' => array(
      'attributes' => array(
        'title' => '',
      ),
      'identifier' => 'main-menu_grid-portfolio:<nolink>',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 1,
    'expanded' => 1,
    'weight' => -49,
    'customized' => 1,
    'parent_identifier' => 'main-menu_portfolio:portfolio',
  );
  // Exported menu link: main-menu_gridstack-view:uuid/node/06f8b908-96a6-4fb1-a7a6-d443b8ed2f1b.
  $menu_links['main-menu_gridstack-view:uuid/node/06f8b908-96a6-4fb1-a7a6-d443b8ed2f1b'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/06f8b908-96a6-4fb1-a7a6-d443b8ed2f1b',
    'router_path' => 'uuid',
    'link_title' => 'GridStack View',
    'options' => array(
      'attributes' => array(
        'title' => '',
      ),
      'identifier' => 'main-menu_gridstack-view:uuid/node/06f8b908-96a6-4fb1-a7a6-d443b8ed2f1b',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -49,
    'customized' => 1,
    'uuid' => '06f8b908-96a6-4fb1-a7a6-d443b8ed2f1b',
    'vuuid' => 'ef3c1e96-6900-49d4-91e7-205abf309a3a',
    'parent_identifier' => 'main-menu_content-elements:<nolink>',
  );
  // Exported menu link: main-menu_home-app-landing-page:uuid/node/a32afdd3-e3b0-4afb-9b9d-fca4ee53e917.
  $menu_links['main-menu_home-app-landing-page:uuid/node/a32afdd3-e3b0-4afb-9b9d-fca4ee53e917'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/a32afdd3-e3b0-4afb-9b9d-fca4ee53e917',
    'router_path' => 'uuid',
    'link_title' => 'Home App Landing Page',
    'options' => array(
      'identifier' => 'main-menu_home-app-landing-page:uuid/node/a32afdd3-e3b0-4afb-9b9d-fca4ee53e917',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 0,
    'uuid' => 'a32afdd3-e3b0-4afb-9b9d-fca4ee53e917',
    'vuuid' => 'fde19d52-9964-421c-9c1e-f79a27557e38',
    'parent_identifier' => 'main-menu_home:uuid/node/5ba48b9e-63be-4e62-a816-aa3a95159c8a',
  );
  // Exported menu link: main-menu_home-basic:uuid/node/fc35b67a-3cea-4e3b-bfc7-17018413f4d6.
  $menu_links['main-menu_home-basic:uuid/node/fc35b67a-3cea-4e3b-bfc7-17018413f4d6'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/fc35b67a-3cea-4e3b-bfc7-17018413f4d6',
    'router_path' => 'uuid',
    'link_title' => 'Home Basic',
    'options' => array(
      'identifier' => 'main-menu_home-basic:uuid/node/fc35b67a-3cea-4e3b-bfc7-17018413f4d6',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 0,
    'uuid' => 'fc35b67a-3cea-4e3b-bfc7-17018413f4d6',
    'vuuid' => '44177503-5985-4152-9338-2dda7170f882',
    'parent_identifier' => 'main-menu_home:uuid/node/5ba48b9e-63be-4e62-a816-aa3a95159c8a',
  );
  // Exported menu link: main-menu_home-blog-classic:uuid/node/703a60cd-2aa6-42ae-8ef9-cb207933bf35.
  $menu_links['main-menu_home-blog-classic:uuid/node/703a60cd-2aa6-42ae-8ef9-cb207933bf35'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/703a60cd-2aa6-42ae-8ef9-cb207933bf35',
    'router_path' => 'uuid',
    'link_title' => 'Home Blog Classic',
    'options' => array(
      'identifier' => 'main-menu_home-blog-classic:uuid/node/703a60cd-2aa6-42ae-8ef9-cb207933bf35',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 0,
    'uuid' => '703a60cd-2aa6-42ae-8ef9-cb207933bf35',
    'vuuid' => '25829d44-b3b3-4092-83a8-9b5681d2b102',
    'parent_identifier' => 'main-menu_home:uuid/node/5ba48b9e-63be-4e62-a816-aa3a95159c8a',
  );
  // Exported menu link: main-menu_home-business-clean:uuid/node/760f2195-e3fd-4957-ac92-410530f39825.
  $menu_links['main-menu_home-business-clean:uuid/node/760f2195-e3fd-4957-ac92-410530f39825'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/760f2195-e3fd-4957-ac92-410530f39825',
    'router_path' => 'uuid',
    'link_title' => 'Home Business Clean',
    'options' => array(
      'identifier' => 'main-menu_home-business-clean:uuid/node/760f2195-e3fd-4957-ac92-410530f39825',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 0,
    'uuid' => '760f2195-e3fd-4957-ac92-410530f39825',
    'vuuid' => '19701731-adbf-472c-a19f-78938e34b4e4',
    'parent_identifier' => 'main-menu_home:uuid/node/5ba48b9e-63be-4e62-a816-aa3a95159c8a',
  );
  // Exported menu link: main-menu_home-canvas:uuid/node/2bc7e0bd-0597-455f-9730-a058acce07dd.
  $menu_links['main-menu_home-canvas:uuid/node/2bc7e0bd-0597-455f-9730-a058acce07dd'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/2bc7e0bd-0597-455f-9730-a058acce07dd',
    'router_path' => 'uuid',
    'link_title' => 'Home Canvas',
    'options' => array(
      'identifier' => 'main-menu_home-canvas:uuid/node/2bc7e0bd-0597-455f-9730-a058acce07dd',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 0,
    'uuid' => '2bc7e0bd-0597-455f-9730-a058acce07dd',
    'vuuid' => 'cd8e7ccd-2138-475e-a33d-b9b4a5db922f',
    'parent_identifier' => 'main-menu_home:uuid/node/5ba48b9e-63be-4e62-a816-aa3a95159c8a',
  );
  // Exported menu link: main-menu_home-main-demo:uuid/node/c8982be9-90c8-4813-ad2d-87c0934213e4.
  $menu_links['main-menu_home-main-demo:uuid/node/c8982be9-90c8-4813-ad2d-87c0934213e4'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/c8982be9-90c8-4813-ad2d-87c0934213e4',
    'router_path' => 'uuid',
    'link_title' => 'Home Main Demo',
    'options' => array(
      'identifier' => 'main-menu_home-main-demo:uuid/node/c8982be9-90c8-4813-ad2d-87c0934213e4',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 0,
    'uuid' => 'c8982be9-90c8-4813-ad2d-87c0934213e4',
    'vuuid' => 'db9d4044-86a2-4ca3-a3ec-411bbb24ff68',
    'parent_identifier' => 'main-menu_home:uuid/node/5ba48b9e-63be-4e62-a816-aa3a95159c8a',
  );
  // Exported menu link: main-menu_home:uuid/node/5ba48b9e-63be-4e62-a816-aa3a95159c8a.
  $menu_links['main-menu_home:uuid/node/5ba48b9e-63be-4e62-a816-aa3a95159c8a'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/5ba48b9e-63be-4e62-a816-aa3a95159c8a',
    'router_path' => 'uuid',
    'link_title' => 'Home',
    'options' => array(
      'attributes' => array(
        'title' => '',
      ),
      'identifier' => 'main-menu_home:uuid/node/5ba48b9e-63be-4e62-a816-aa3a95159c8a',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 1,
    'expanded' => 1,
    'weight' => -50,
    'customized' => 0,
    'uuid' => '5ba48b9e-63be-4e62-a816-aa3a95159c8a',
    'vuuid' => '03252fad-007b-4c27-ac6f-b803312bb580',
  );
  // Exported menu link: main-menu_homepage-portfolio-1:uuid/node/d880e681-e7a1-494f-b182-f7da873cff88.
  $menu_links['main-menu_homepage-portfolio-1:uuid/node/d880e681-e7a1-494f-b182-f7da873cff88'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/d880e681-e7a1-494f-b182-f7da873cff88',
    'router_path' => 'uuid',
    'link_title' => 'Homepage Portfolio 1',
    'options' => array(
      'attributes' => array(),
      'identifier' => 'main-menu_homepage-portfolio-1:uuid/node/d880e681-e7a1-494f-b182-f7da873cff88',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 0,
    'uuid' => 'd880e681-e7a1-494f-b182-f7da873cff88',
    'vuuid' => '3ae73e75-71bd-415c-ad85-9ca16b97bb62',
    'parent_identifier' => 'main-menu_home:uuid/node/5ba48b9e-63be-4e62-a816-aa3a95159c8a',
  );
  // Exported menu link: main-menu_icon-box:uuid/node/8cee9fbf-2933-45e5-9c12-b6aab9075cfb.
  $menu_links['main-menu_icon-box:uuid/node/8cee9fbf-2933-45e5-9c12-b6aab9075cfb'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/8cee9fbf-2933-45e5-9c12-b6aab9075cfb',
    'router_path' => 'uuid',
    'link_title' => 'Icon Box',
    'options' => array(
      'identifier' => 'main-menu_icon-box:uuid/node/8cee9fbf-2933-45e5-9c12-b6aab9075cfb',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -50,
    'customized' => 1,
    'uuid' => '8cee9fbf-2933-45e5-9c12-b6aab9075cfb',
    'vuuid' => 'e73e5b8e-9b31-46bf-bd89-599cdd4c4e8b',
    'parent_identifier' => 'main-menu_content-elements:<nolink>',
  );
  // Exported menu link: main-menu_icon-well:uuid/node/5ff84c19-e9e1-4760-9253-abbedce064cd.
  $menu_links['main-menu_icon-well:uuid/node/5ff84c19-e9e1-4760-9253-abbedce064cd'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/5ff84c19-e9e1-4760-9253-abbedce064cd',
    'router_path' => 'uuid',
    'link_title' => 'Icon Well',
    'options' => array(
      'identifier' => 'main-menu_icon-well:uuid/node/5ff84c19-e9e1-4760-9253-abbedce064cd',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -45,
    'customized' => 1,
    'uuid' => '5ff84c19-e9e1-4760-9253-abbedce064cd',
    'vuuid' => '051fdbbd-87d9-4b0f-b86e-00efe485cd89',
    'parent_identifier' => 'main-menu_content-elements:<nolink>',
  );
  // Exported menu link: main-menu_icons:uuid/node/4b2cf32d-ba09-4ba9-9879-5a9bd359b598.
  $menu_links['main-menu_icons:uuid/node/4b2cf32d-ba09-4ba9-9879-5a9bd359b598'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/4b2cf32d-ba09-4ba9-9879-5a9bd359b598',
    'router_path' => 'uuid',
    'link_title' => 'Icons',
    'options' => array(
      'identifier' => 'main-menu_icons:uuid/node/4b2cf32d-ba09-4ba9-9879-5a9bd359b598',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -48,
    'customized' => 1,
    'uuid' => '4b2cf32d-ba09-4ba9-9879-5a9bd359b598',
    'vuuid' => 'cde5c9a1-35cc-4098-940a-2ea94bbb1e35',
    'parent_identifier' => 'main-menu_media-elements:<nolink>',
  );
  // Exported menu link: main-menu_image-element--slider:uuid/node/0d2550e9-bc2f-42f7-9f4a-27f5ad950b94.
  $menu_links['main-menu_image-element--slider:uuid/node/0d2550e9-bc2f-42f7-9f4a-27f5ad950b94'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/0d2550e9-bc2f-42f7-9f4a-27f5ad950b94',
    'router_path' => 'uuid',
    'link_title' => 'Image Element & Slider',
    'options' => array(
      'identifier' => 'main-menu_image-element--slider:uuid/node/0d2550e9-bc2f-42f7-9f4a-27f5ad950b94',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -42,
    'customized' => 1,
    'uuid' => '0d2550e9-bc2f-42f7-9f4a-27f5ad950b94',
    'vuuid' => '23f5c7cf-a776-4864-8b68-59c1b0caf259',
    'parent_identifier' => 'main-menu_media-elements:<nolink>',
  );
  // Exported menu link: main-menu_interactive-elements:<nolink>.
  $menu_links['main-menu_interactive-elements:<nolink>'] = array(
    'menu_name' => 'main-menu',
    'link_path' => '<nolink>',
    'router_path' => '<nolink>',
    'link_title' => 'Interactive Elements',
    'options' => array(
      'attributes' => array(
        'title' => '',
      ),
      'identifier' => 'main-menu_interactive-elements:<nolink>',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 1,
    'expanded' => 1,
    'weight' => -47,
    'customized' => 1,
    'parent_identifier' => 'main-menu_elements:<nolink>',
  );
  // Exported menu link: main-menu_jumbotron:uuid/node/bfb6a4e5-3557-489b-b949-872f6dd0ebb2.
  $menu_links['main-menu_jumbotron:uuid/node/bfb6a4e5-3557-489b-b949-872f6dd0ebb2'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/bfb6a4e5-3557-489b-b949-872f6dd0ebb2',
    'router_path' => 'uuid',
    'link_title' => 'Jumbotron',
    'options' => array(
      'identifier' => 'main-menu_jumbotron:uuid/node/bfb6a4e5-3557-489b-b949-872f6dd0ebb2',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -44,
    'customized' => 1,
    'uuid' => 'bfb6a4e5-3557-489b-b949-872f6dd0ebb2',
    'vuuid' => '3f9f6025-5786-4b5a-96e7-59c79a3e0bf4',
    'parent_identifier' => 'main-menu_layout-elements:<nolink>',
  );
  // Exported menu link: main-menu_layout-elements:<nolink>.
  $menu_links['main-menu_layout-elements:<nolink>'] = array(
    'menu_name' => 'main-menu',
    'link_path' => '<nolink>',
    'router_path' => '<nolink>',
    'link_title' => 'Layout Elements',
    'options' => array(
      'attributes' => array(
        'title' => '',
      ),
      'identifier' => 'main-menu_layout-elements:<nolink>',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 1,
    'expanded' => 1,
    'weight' => -50,
    'customized' => 1,
    'parent_identifier' => 'main-menu_elements:<nolink>',
  );
  // Exported menu link: main-menu_lead:uuid/node/9e0ff233-9546-4277-bac0-a2e6cb36c8a7.
  $menu_links['main-menu_lead:uuid/node/9e0ff233-9546-4277-bac0-a2e6cb36c8a7'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/9e0ff233-9546-4277-bac0-a2e6cb36c8a7',
    'router_path' => 'uuid',
    'link_title' => 'Lead',
    'options' => array(
      'identifier' => 'main-menu_lead:uuid/node/9e0ff233-9546-4277-bac0-a2e6cb36c8a7',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -42,
    'customized' => 1,
    'uuid' => '9e0ff233-9546-4277-bac0-a2e6cb36c8a7',
    'vuuid' => 'f9c4c106-0301-4714-9ae3-6616e69c9149',
    'parent_identifier' => 'main-menu_layout-elements:<nolink>',
  );
  // Exported menu link: main-menu_masonry-portfolio:<nolink>.
  $menu_links['main-menu_masonry-portfolio:<nolink>'] = array(
    'menu_name' => 'main-menu',
    'link_path' => '<nolink>',
    'router_path' => '<nolink>',
    'link_title' => 'Masonry Portfolio',
    'options' => array(
      'attributes' => array(
        'title' => '',
      ),
      'identifier' => 'main-menu_masonry-portfolio:<nolink>',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 1,
    'expanded' => 1,
    'weight' => -50,
    'customized' => 1,
    'parent_identifier' => 'main-menu_portfolio:portfolio',
  );
  // Exported menu link: main-menu_media-elements:<nolink>.
  $menu_links['main-menu_media-elements:<nolink>'] = array(
    'menu_name' => 'main-menu',
    'link_path' => '<nolink>',
    'router_path' => '<nolink>',
    'link_title' => 'Media Elements',
    'options' => array(
      'attributes' => array(
        'title' => '',
      ),
      'identifier' => 'main-menu_media-elements:<nolink>',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 1,
    'expanded' => 1,
    'weight' => -48,
    'customized' => 1,
    'parent_identifier' => 'main-menu_elements:<nolink>',
  );
  // Exported menu link: main-menu_motion-image-box:uuid/node/448c021f-1d62-43a3-aaa9-6111e2dca456.
  $menu_links['main-menu_motion-image-box:uuid/node/448c021f-1d62-43a3-aaa9-6111e2dca456'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/448c021f-1d62-43a3-aaa9-6111e2dca456',
    'router_path' => 'uuid',
    'link_title' => 'Motion Image Box',
    'options' => array(
      'identifier' => 'main-menu_motion-image-box:uuid/node/448c021f-1d62-43a3-aaa9-6111e2dca456',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -43,
    'customized' => 1,
    'uuid' => '448c021f-1d62-43a3-aaa9-6111e2dca456',
    'vuuid' => '07927bb8-c7e2-4077-8596-4d689421a8f0',
    'parent_identifier' => 'main-menu_media-elements:<nolink>',
  );
  // Exported menu link: main-menu_news:news.
  $menu_links['main-menu_news:news'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'news',
    'router_path' => 'news',
    'link_title' => 'News',
    'options' => array(
      'identifier' => 'main-menu_news:news',
    ),
    'module' => 'system',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -44,
    'customized' => 1,
  );
  // Exported menu link: main-menu_pages:uuid/node/5810252c-ebbb-42e3-9523-fbedc419dc4e.
  $menu_links['main-menu_pages:uuid/node/5810252c-ebbb-42e3-9523-fbedc419dc4e'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/5810252c-ebbb-42e3-9523-fbedc419dc4e',
    'router_path' => 'uuid',
    'link_title' => 'Pages',
    'options' => array(
      'attributes' => array(
        'title' => '',
      ),
      'identifier' => 'main-menu_pages:uuid/node/5810252c-ebbb-42e3-9523-fbedc419dc4e',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 1,
    'expanded' => 1,
    'weight' => -47,
    'customized' => 0,
    'uuid' => '5810252c-ebbb-42e3-9523-fbedc419dc4e',
    'vuuid' => '1447e5a8-ba0a-4427-a99d-23bd3e83faed',
  );
  // Exported menu link: main-menu_panel:uuid/node/2e6d0201-12ac-40ce-8c42-15b8251b7902.
  $menu_links['main-menu_panel:uuid/node/2e6d0201-12ac-40ce-8c42-15b8251b7902'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/2e6d0201-12ac-40ce-8c42-15b8251b7902',
    'router_path' => 'uuid',
    'link_title' => 'Panel',
    'options' => array(
      'identifier' => 'main-menu_panel:uuid/node/2e6d0201-12ac-40ce-8c42-15b8251b7902',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -45,
    'customized' => 1,
    'uuid' => '2e6d0201-12ac-40ce-8c42-15b8251b7902',
    'vuuid' => '0a078217-c6f4-4b13-909d-f15941e8ae5d',
    'parent_identifier' => 'main-menu_layout-elements:<nolink>',
  );
  // Exported menu link: main-menu_portfolio-1-column-with-excerpt:portfolio/1excerpt.
  $menu_links['main-menu_portfolio-1-column-with-excerpt:portfolio/1excerpt'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'portfolio/1excerpt',
    'router_path' => 'portfolio/1excerpt',
    'link_title' => 'Portfolio 1 Column with Excerpt',
    'options' => array(
      'identifier' => 'main-menu_portfolio-1-column-with-excerpt:portfolio/1excerpt',
    ),
    'module' => 'system',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -50,
    'customized' => 1,
    'parent_identifier' => 'main-menu_grid-portfolio:<nolink>',
  );
  // Exported menu link: main-menu_portfolio-1-column:portfolio/1.
  $menu_links['main-menu_portfolio-1-column:portfolio/1'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'portfolio/1',
    'router_path' => 'portfolio/1',
    'link_title' => 'Portfolio 1 Column',
    'options' => array(
      'identifier' => 'main-menu_portfolio-1-column:portfolio/1',
    ),
    'module' => 'system',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -49,
    'customized' => 1,
    'parent_identifier' => 'main-menu_grid-portfolio:<nolink>',
  );
  // Exported menu link: main-menu_portfolio-2-columns:portfolio/2.
  $menu_links['main-menu_portfolio-2-columns:portfolio/2'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'portfolio/2',
    'router_path' => 'portfolio/2',
    'link_title' => 'Portfolio 2 Columns',
    'options' => array(
      'identifier' => 'main-menu_portfolio-2-columns:portfolio/2',
    ),
    'module' => 'system',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -48,
    'customized' => 1,
    'parent_identifier' => 'main-menu_grid-portfolio:<nolink>',
  );
  // Exported menu link: main-menu_portfolio-3-columns:portfolio/3.
  $menu_links['main-menu_portfolio-3-columns:portfolio/3'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'portfolio/3',
    'router_path' => 'portfolio/3',
    'link_title' => 'Portfolio 3 Columns',
    'options' => array(
      'identifier' => 'main-menu_portfolio-3-columns:portfolio/3',
    ),
    'module' => 'system',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -47,
    'customized' => 1,
    'parent_identifier' => 'main-menu_grid-portfolio:<nolink>',
  );
  // Exported menu link: main-menu_portfolio-4-columns:portfolio.
  $menu_links['main-menu_portfolio-4-columns:portfolio'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'portfolio',
    'router_path' => 'portfolio',
    'link_title' => 'Portfolio 4 Columns',
    'options' => array(
      'attributes' => array(
        'title' => '',
      ),
      'identifier' => 'main-menu_portfolio-4-columns:portfolio',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -46,
    'customized' => 1,
    'parent_identifier' => 'main-menu_grid-portfolio:<nolink>',
  );
  // Exported menu link: main-menu_portfolio-6-columns:portfolio/6.
  $menu_links['main-menu_portfolio-6-columns:portfolio/6'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'portfolio/6',
    'router_path' => 'portfolio/6',
    'link_title' => 'Portfolio 6 Columns',
    'options' => array(
      'identifier' => 'main-menu_portfolio-6-columns:portfolio/6',
    ),
    'module' => 'system',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -46,
    'customized' => 1,
    'parent_identifier' => 'main-menu_grid-portfolio:<nolink>',
  );
  // Exported menu link: main-menu_portfolio-masonry-2-with-excerpt:portfolio/v2excerpt.
  $menu_links['main-menu_portfolio-masonry-2-with-excerpt:portfolio/v2excerpt'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'portfolio/v2excerpt',
    'router_path' => 'portfolio/v2excerpt',
    'link_title' => 'Portfolio Masonry 2 with Excerpt',
    'options' => array(
      'identifier' => 'main-menu_portfolio-masonry-2-with-excerpt:portfolio/v2excerpt',
    ),
    'module' => 'system',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -46,
    'customized' => 1,
    'parent_identifier' => 'main-menu_masonry-portfolio:<nolink>',
  );
  // Exported menu link: main-menu_portfolio-masonry-2:portfolio/v2.
  $menu_links['main-menu_portfolio-masonry-2:portfolio/v2'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'portfolio/v2',
    'router_path' => 'portfolio/v2',
    'link_title' => 'Portfolio Masonry 2',
    'options' => array(
      'identifier' => 'main-menu_portfolio-masonry-2:portfolio/v2',
    ),
    'module' => 'system',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -50,
    'customized' => 1,
    'parent_identifier' => 'main-menu_masonry-portfolio:<nolink>',
  );
  // Exported menu link: main-menu_portfolio-masonry-3-with-excerpt:portfolio/v3excerpt.
  $menu_links['main-menu_portfolio-masonry-3-with-excerpt:portfolio/v3excerpt'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'portfolio/v3excerpt',
    'router_path' => 'portfolio/v3excerpt',
    'link_title' => 'Portfolio Masonry 3 with Excerpt',
    'options' => array(
      'identifier' => 'main-menu_portfolio-masonry-3-with-excerpt:portfolio/v3excerpt',
    ),
    'module' => 'system',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -45,
    'customized' => 1,
    'parent_identifier' => 'main-menu_masonry-portfolio:<nolink>',
  );
  // Exported menu link: main-menu_portfolio-masonry-3:portfolio/v3.
  $menu_links['main-menu_portfolio-masonry-3:portfolio/v3'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'portfolio/v3',
    'router_path' => 'portfolio/v3',
    'link_title' => 'Portfolio Masonry 3',
    'options' => array(
      'identifier' => 'main-menu_portfolio-masonry-3:portfolio/v3',
    ),
    'module' => 'system',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -49,
    'customized' => 1,
    'parent_identifier' => 'main-menu_masonry-portfolio:<nolink>',
  );
  // Exported menu link: main-menu_portfolio-masonry-4-with-excerpt:portfolio/v4excerpt.
  $menu_links['main-menu_portfolio-masonry-4-with-excerpt:portfolio/v4excerpt'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'portfolio/v4excerpt',
    'router_path' => 'portfolio/v4excerpt',
    'link_title' => 'Portfolio Masonry 4 with Excerpt',
    'options' => array(
      'identifier' => 'main-menu_portfolio-masonry-4-with-excerpt:portfolio/v4excerpt',
    ),
    'module' => 'system',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -44,
    'customized' => 1,
    'parent_identifier' => 'main-menu_masonry-portfolio:<nolink>',
  );
  // Exported menu link: main-menu_portfolio-masonry-4:portfolio/v4.
  $menu_links['main-menu_portfolio-masonry-4:portfolio/v4'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'portfolio/v4',
    'router_path' => 'portfolio/v4',
    'link_title' => 'Portfolio Masonry 4',
    'options' => array(
      'identifier' => 'main-menu_portfolio-masonry-4:portfolio/v4',
    ),
    'module' => 'system',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -48,
    'customized' => 1,
    'parent_identifier' => 'main-menu_masonry-portfolio:<nolink>',
  );
  // Exported menu link: main-menu_portfolio-masonry-6:portfolio/v6.
  $menu_links['main-menu_portfolio-masonry-6:portfolio/v6'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'portfolio/v6',
    'router_path' => 'portfolio/v6',
    'link_title' => 'Portfolio Masonry 6',
    'options' => array(
      'identifier' => 'main-menu_portfolio-masonry-6:portfolio/v6',
    ),
    'module' => 'system',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -47,
    'customized' => 1,
    'parent_identifier' => 'main-menu_masonry-portfolio:<nolink>',
  );
  // Exported menu link: main-menu_portfolio:portfolio.
  $menu_links['main-menu_portfolio:portfolio'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'portfolio',
    'router_path' => 'portfolio',
    'link_title' => 'Portfolio',
    'options' => array(
      'attributes' => array(
        'title' => '',
      ),
      'identifier' => 'main-menu_portfolio:portfolio',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 1,
    'expanded' => 1,
    'weight' => -46,
    'customized' => 1,
  );
  // Exported menu link: main-menu_positioned-layers:uuid/node/a5fc2ec5-7d47-40cb-98c3-50916154e18e.
  $menu_links['main-menu_positioned-layers:uuid/node/a5fc2ec5-7d47-40cb-98c3-50916154e18e'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/a5fc2ec5-7d47-40cb-98c3-50916154e18e',
    'router_path' => 'uuid',
    'link_title' => 'Positioned Layers',
    'options' => array(
      'identifier' => 'main-menu_positioned-layers:uuid/node/a5fc2ec5-7d47-40cb-98c3-50916154e18e',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -49,
    'customized' => 1,
    'uuid' => 'a5fc2ec5-7d47-40cb-98c3-50916154e18e',
    'vuuid' => 'eefa8025-6e5d-4440-8ef5-e720756a7468',
    'parent_identifier' => 'main-menu_layout-elements:<nolink>',
  );
  // Exported menu link: main-menu_premium-portfolio:<nolink>.
  $menu_links['main-menu_premium-portfolio:<nolink>'] = array(
    'menu_name' => 'main-menu',
    'link_path' => '<nolink>',
    'router_path' => '<nolink>',
    'link_title' => 'Premium Portfolio',
    'options' => array(
      'attributes' => array(
        'title' => '',
      ),
      'identifier' => 'main-menu_premium-portfolio:<nolink>',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 1,
    'expanded' => 1,
    'weight' => -48,
    'customized' => 1,
    'parent_identifier' => 'main-menu_portfolio:portfolio',
  );
  // Exported menu link: main-menu_pricing-page:uuid/node/e9a73a03-7034-42a9-8a77-5ff90c98a0d2.
  $menu_links['main-menu_pricing-page:uuid/node/e9a73a03-7034-42a9-8a77-5ff90c98a0d2'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/e9a73a03-7034-42a9-8a77-5ff90c98a0d2',
    'router_path' => 'uuid',
    'link_title' => 'Pricing Page',
    'options' => array(
      'identifier' => 'main-menu_pricing-page:uuid/node/e9a73a03-7034-42a9-8a77-5ff90c98a0d2',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -46,
    'customized' => 1,
    'uuid' => 'e9a73a03-7034-42a9-8a77-5ff90c98a0d2',
    'vuuid' => '2cf226a5-3a13-45a9-91ba-08717587cfd7',
    'parent_identifier' => 'main-menu_pages:uuid/node/5810252c-ebbb-42e3-9523-fbedc419dc4e',
  );
  // Exported menu link: main-menu_pricing-table:uuid/node/e54ed492-aa67-4f17-84c2-a841dac84118.
  $menu_links['main-menu_pricing-table:uuid/node/e54ed492-aa67-4f17-84c2-a841dac84118'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/e54ed492-aa67-4f17-84c2-a841dac84118',
    'router_path' => 'uuid',
    'link_title' => 'Pricing Table',
    'options' => array(
      'identifier' => 'main-menu_pricing-table:uuid/node/e54ed492-aa67-4f17-84c2-a841dac84118',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -47,
    'customized' => 1,
    'uuid' => 'e54ed492-aa67-4f17-84c2-a841dac84118',
    'vuuid' => 'b92fd1f1-6f2f-4907-988f-194836b7de30',
    'parent_identifier' => 'main-menu_media-elements:<nolink>',
  );
  // Exported menu link: main-menu_quote-slider:uuid/node/d495cf25-fc13-4103-a876-c71b190c421c.
  $menu_links['main-menu_quote-slider:uuid/node/d495cf25-fc13-4103-a876-c71b190c421c'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/d495cf25-fc13-4103-a876-c71b190c421c',
    'router_path' => 'uuid',
    'link_title' => 'Quote Slider',
    'options' => array(
      'identifier' => 'main-menu_quote-slider:uuid/node/d495cf25-fc13-4103-a876-c71b190c421c',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -43,
    'customized' => 1,
    'uuid' => 'd495cf25-fc13-4103-a876-c71b190c421c',
    'vuuid' => 'da2e2f10-0ed8-450e-9cd6-c6111de2b8ff',
    'parent_identifier' => 'main-menu_interactive-elements:<nolink>',
  );
  // Exported menu link: main-menu_registration-landing-1:uuid/node/73824210-432e-4f4d-b0e8-4cc1866bb6b0.
  $menu_links['main-menu_registration-landing-1:uuid/node/73824210-432e-4f4d-b0e8-4cc1866bb6b0'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/73824210-432e-4f4d-b0e8-4cc1866bb6b0',
    'router_path' => 'uuid',
    'link_title' => 'Registration Landing 1',
    'options' => array(
      'identifier' => 'main-menu_registration-landing-1:uuid/node/73824210-432e-4f4d-b0e8-4cc1866bb6b0',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -45,
    'customized' => 1,
    'uuid' => '73824210-432e-4f4d-b0e8-4cc1866bb6b0',
    'vuuid' => 'c874d29d-9d3d-418d-b224-ac34c48c1da4',
    'parent_identifier' => 'main-menu_pages:uuid/node/5810252c-ebbb-42e3-9523-fbedc419dc4e',
  );
  // Exported menu link: main-menu_registration-landing-2:uuid/node/f33609ac-acba-4168-ba00-0f56d82e8b33.
  $menu_links['main-menu_registration-landing-2:uuid/node/f33609ac-acba-4168-ba00-0f56d82e8b33'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/f33609ac-acba-4168-ba00-0f56d82e8b33',
    'router_path' => 'uuid',
    'link_title' => 'Registration Landing 2',
    'options' => array(
      'identifier' => 'main-menu_registration-landing-2:uuid/node/f33609ac-acba-4168-ba00-0f56d82e8b33',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -44,
    'customized' => 1,
    'uuid' => 'f33609ac-acba-4168-ba00-0f56d82e8b33',
    'vuuid' => '9dfabe4d-dc9d-44ad-89a6-8f3c8059a805',
    'parent_identifier' => 'main-menu_pages:uuid/node/5810252c-ebbb-42e3-9523-fbedc419dc4e',
  );
  // Exported menu link: main-menu_restaurant-menu-page:uuid/node/9ddaf86c-5040-4a76-986a-cd6621deacba.
  $menu_links['main-menu_restaurant-menu-page:uuid/node/9ddaf86c-5040-4a76-986a-cd6621deacba'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/9ddaf86c-5040-4a76-986a-cd6621deacba',
    'router_path' => 'uuid',
    'link_title' => 'Restaurant Menu Page',
    'options' => array(
      'identifier' => 'main-menu_restaurant-menu-page:uuid/node/9ddaf86c-5040-4a76-986a-cd6621deacba',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -43,
    'customized' => 1,
    'uuid' => '9ddaf86c-5040-4a76-986a-cd6621deacba',
    'vuuid' => '92c911af-7896-4ef9-a548-e8f8f846d0be',
    'parent_identifier' => 'main-menu_pages:uuid/node/5810252c-ebbb-42e3-9523-fbedc419dc4e',
  );
  // Exported menu link: main-menu_revolution-slider:uuid/node/1a7f1fac-caa4-42b6-8c3e-46fef3fc12e1.
  $menu_links['main-menu_revolution-slider:uuid/node/1a7f1fac-caa4-42b6-8c3e-46fef3fc12e1'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/1a7f1fac-caa4-42b6-8c3e-46fef3fc12e1',
    'router_path' => 'uuid',
    'link_title' => 'Revolution Slider',
    'options' => array(
      'identifier' => 'main-menu_revolution-slider:uuid/node/1a7f1fac-caa4-42b6-8c3e-46fef3fc12e1',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -44,
    'customized' => 1,
    'uuid' => '1a7f1fac-caa4-42b6-8c3e-46fef3fc12e1',
    'vuuid' => '2301c90a-8504-4c32-bc4f-b50e0e9cd855',
    'parent_identifier' => 'main-menu_interactive-elements:<nolink>',
  );
  // Exported menu link: main-menu_sections-and-backgrounds:uuid/node/969e7879-63f5-464c-a8af-6fb131a1aeed.
  $menu_links['main-menu_sections-and-backgrounds:uuid/node/969e7879-63f5-464c-a8af-6fb131a1aeed'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/969e7879-63f5-464c-a8af-6fb131a1aeed',
    'router_path' => 'uuid',
    'link_title' => 'Sections and Backgrounds',
    'options' => array(
      'identifier' => 'main-menu_sections-and-backgrounds:uuid/node/969e7879-63f5-464c-a8af-6fb131a1aeed',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -48,
    'customized' => 1,
    'uuid' => '969e7879-63f5-464c-a8af-6fb131a1aeed',
    'vuuid' => '21773237-585b-48fd-bee9-ab2b34b1b1d5',
    'parent_identifier' => 'main-menu_layout-elements:<nolink>',
  );
  // Exported menu link: main-menu_services-page:uuid/node/e31a7eb7-7117-45c3-ad3f-91f8c6589814.
  $menu_links['main-menu_services-page:uuid/node/e31a7eb7-7117-45c3-ad3f-91f8c6589814'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/e31a7eb7-7117-45c3-ad3f-91f8c6589814',
    'router_path' => 'uuid',
    'link_title' => 'Services Page',
    'options' => array(
      'identifier' => 'main-menu_services-page:uuid/node/e31a7eb7-7117-45c3-ad3f-91f8c6589814',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -42,
    'customized' => 1,
    'uuid' => 'e31a7eb7-7117-45c3-ad3f-91f8c6589814',
    'vuuid' => '7ab46d20-caed-485d-afa7-fa3128eeb28f',
    'parent_identifier' => 'main-menu_pages:uuid/node/5810252c-ebbb-42e3-9523-fbedc419dc4e',
  );
  // Exported menu link: main-menu_social-links:uuid/node/887edc90-eb66-4e94-9757-645e9221a364.
  $menu_links['main-menu_social-links:uuid/node/887edc90-eb66-4e94-9757-645e9221a364'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/887edc90-eb66-4e94-9757-645e9221a364',
    'router_path' => 'uuid',
    'link_title' => 'Social Links',
    'options' => array(
      'identifier' => 'main-menu_social-links:uuid/node/887edc90-eb66-4e94-9757-645e9221a364',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -49,
    'customized' => 1,
    'uuid' => '887edc90-eb66-4e94-9757-645e9221a364',
    'vuuid' => '20b1b632-a64c-4460-8d0b-42c3243687b4',
    'parent_identifier' => 'main-menu_interactive-elements:<nolink>',
  );
  // Exported menu link: main-menu_tabs:uuid/node/92e308f2-1208-4b67-ba2b-04dbe2d5833a.
  $menu_links['main-menu_tabs:uuid/node/92e308f2-1208-4b67-ba2b-04dbe2d5833a'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/92e308f2-1208-4b67-ba2b-04dbe2d5833a',
    'router_path' => 'uuid',
    'link_title' => 'Tabs',
    'options' => array(
      'identifier' => 'main-menu_tabs:uuid/node/92e308f2-1208-4b67-ba2b-04dbe2d5833a',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -48,
    'customized' => 1,
    'uuid' => '92e308f2-1208-4b67-ba2b-04dbe2d5833a',
    'vuuid' => 'dbe873a1-b717-411f-861c-03caf851204f',
    'parent_identifier' => 'main-menu_content-elements:<nolink>',
  );
  // Exported menu link: main-menu_team-box:uuid/node/706f5a68-da75-4834-a050-9de1b4d58fd6.
  $menu_links['main-menu_team-box:uuid/node/706f5a68-da75-4834-a050-9de1b4d58fd6'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/706f5a68-da75-4834-a050-9de1b4d58fd6',
    'router_path' => 'uuid',
    'link_title' => 'Team Box',
    'options' => array(
      'identifier' => 'main-menu_team-box:uuid/node/706f5a68-da75-4834-a050-9de1b4d58fd6',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -45,
    'customized' => 1,
    'uuid' => '706f5a68-da75-4834-a050-9de1b4d58fd6',
    'vuuid' => 'a39ed951-5dcf-4450-8303-687639500698',
    'parent_identifier' => 'main-menu_media-elements:<nolink>',
  );
  // Exported menu link: main-menu_team-page:uuid/node/ef10c794-ab7b-4983-9c72-c59899b4a308.
  $menu_links['main-menu_team-page:uuid/node/ef10c794-ab7b-4983-9c72-c59899b4a308'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/ef10c794-ab7b-4983-9c72-c59899b4a308',
    'router_path' => 'uuid',
    'link_title' => 'Team Page',
    'options' => array(
      'identifier' => 'main-menu_team-page:uuid/node/ef10c794-ab7b-4983-9c72-c59899b4a308',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -41,
    'customized' => 1,
    'uuid' => 'ef10c794-ab7b-4983-9c72-c59899b4a308',
    'vuuid' => '26af07f0-d297-4d83-be33-9a1729abb356',
    'parent_identifier' => 'main-menu_pages:uuid/node/5810252c-ebbb-42e3-9523-fbedc419dc4e',
  );
  // Exported menu link: main-menu_time-line:uuid/node/b50ca955-ea53-4854-a408-6f39a7262093.
  $menu_links['main-menu_time-line:uuid/node/b50ca955-ea53-4854-a408-6f39a7262093'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/b50ca955-ea53-4854-a408-6f39a7262093',
    'router_path' => 'uuid',
    'link_title' => 'Time Line',
    'options' => array(
      'identifier' => 'main-menu_time-line:uuid/node/b50ca955-ea53-4854-a408-6f39a7262093',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -46,
    'customized' => 1,
    'uuid' => 'b50ca955-ea53-4854-a408-6f39a7262093',
    'vuuid' => '17019040-6fc6-4a9e-8dcf-d9a63654bf17',
    'parent_identifier' => 'main-menu_layout-elements:<nolink>',
  );
  // Exported menu link: main-menu_video-element:uuid/node/90e2fdb0-fe08-47e2-8ea5-4e844154920c.
  $menu_links['main-menu_video-element:uuid/node/90e2fdb0-fe08-47e2-8ea5-4e844154920c'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/90e2fdb0-fe08-47e2-8ea5-4e844154920c',
    'router_path' => 'uuid',
    'link_title' => 'Video Element',
    'options' => array(
      'identifier' => 'main-menu_video-element:uuid/node/90e2fdb0-fe08-47e2-8ea5-4e844154920c',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -50,
    'customized' => 1,
    'uuid' => '90e2fdb0-fe08-47e2-8ea5-4e844154920c',
    'vuuid' => '7861edd1-8a95-4cef-a8b8-12a5542b82ef',
    'parent_identifier' => 'main-menu_media-elements:<nolink>',
  );
  // Exported menu link: main-menu_well:uuid/node/ca2e52f4-ec41-4a6b-ae81-6aeef8149192.
  $menu_links['main-menu_well:uuid/node/ca2e52f4-ec41-4a6b-ae81-6aeef8149192'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/ca2e52f4-ec41-4a6b-ae81-6aeef8149192',
    'router_path' => 'uuid',
    'link_title' => 'Well',
    'options' => array(
      'identifier' => 'main-menu_well:uuid/node/ca2e52f4-ec41-4a6b-ae81-6aeef8149192',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -43,
    'customized' => 1,
    'uuid' => 'ca2e52f4-ec41-4a6b-ae81-6aeef8149192',
    'vuuid' => 'c4bf1ef3-d977-478b-be12-62e5a2f40338',
    'parent_identifier' => 'main-menu_layout-elements:<nolink>',
  );

  // Translatables
  // Included for use with string extractors like potx.
  t('About Me');
  t('About Us');
  t('About Us Timeline');
  t('Animation Engine');
  t('Blockquote');
  t('Blog');
  t('Blog Classic Style');
  t('Blog Grid 2 Columns');
  t('Blog Grid 3 Columns');
  t('Blog Grid 4 Columns');
  t('Blog Modern Style');
  t('Buttons');
  t('Call to Action');
  t('Carousel Element');
  t('Circle Counter');
  t('Collapsibles');
  t('Colored Icon Boxes');
  t('Columns');
  t('Contact');
  t('Content Elements');
  t('Count Down Timer');
  t('Counter');
  t('Divider');
  t('Drop Shadow');
  t('Drupal Blocks');
  t('Drupal Views');
  t('Elements');
  t('Events');
  t('FAQ');
  t('Glazed Filter No Spacing');
  t('Glazed Filter With Spacing');
  t('Glazed Full Screen Modal Portfolio');
  t('Glazed Inline Modal Portfolio');
  t('Glazed Lightbox Portfolio');
  t('Google Maps');
  t('Grid Portfolio');
  t('GridStack View');
  t('Home');
  t('Home App Landing Page');
  t('Home Basic');
  t('Home Blog Classic');
  t('Home Business Clean');
  t('Home Canvas');
  t('Home Main Demo');
  t('Homepage Portfolio 1');
  t('Icon Box');
  t('Icon Well');
  t('Icons');
  t('Image Element & Slider');
  t('Interactive Elements');
  t('Jumbotron');
  t('Layout Elements');
  t('Lead');
  t('Masonry Portfolio');
  t('Media Elements');
  t('Motion Image Box');
  t('News');
  t('Pages');
  t('Panel');
  t('Portfolio');
  t('Portfolio 1 Column');
  t('Portfolio 1 Column with Excerpt');
  t('Portfolio 2 Columns');
  t('Portfolio 3 Columns');
  t('Portfolio 4 Columns');
  t('Portfolio 6 Columns');
  t('Portfolio Masonry 2');
  t('Portfolio Masonry 2 with Excerpt');
  t('Portfolio Masonry 3');
  t('Portfolio Masonry 3 with Excerpt');
  t('Portfolio Masonry 4');
  t('Portfolio Masonry 4 with Excerpt');
  t('Portfolio Masonry 6');
  t('Positioned Layers');
  t('Premium Portfolio');
  t('Pricing Page');
  t('Pricing Table');
  t('Quote Slider');
  t('Registration Landing 1');
  t('Registration Landing 2');
  t('Restaurant Menu Page');
  t('Revolution Slider');
  t('Sections and Backgrounds');
  t('Services Page');
  t('Social Links');
  t('Tabs');
  t('Team Box');
  t('Team Page');
  t('Time Line');
  t('Video Element');
  t('Well');

  return $menu_links;
}
