<?php
/**
 * @file
 * glazed_content_homepage_examples.features.menu_links.inc
 */

/**
 * Implements hook_menu_default_menu_links().
 */
function glazed_content_homepage_examples_menu_default_menu_links() {
  $menu_links = array();

  // Exported menu link: main-menu_home-app-landing-page:uuid/node/a32afdd3-e3b0-4afb-9b9d-fca4ee53e917.
  $menu_links['main-menu_home-app-landing-page:uuid/node/a32afdd3-e3b0-4afb-9b9d-fca4ee53e917'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/a32afdd3-e3b0-4afb-9b9d-fca4ee53e917',
    'router_path' => 'uuid',
    'link_title' => 'Home App Landing Page',
    'options' => array(
      'identifier' => 'main-menu_home-app-landing-page:uuid/node/a32afdd3-e3b0-4afb-9b9d-fca4ee53e917',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 0,
    'uuid' => 'a32afdd3-e3b0-4afb-9b9d-fca4ee53e917',
    'vuuid' => 'd03db92c-cce3-486f-a8c5-a4e20e5f5f3e',
    'parent_identifier' => 'main-menu_home:uuid/node/5ba48b9e-63be-4e62-a816-aa3a95159c8a',
  );
  // Exported menu link: main-menu_home-basic:uuid/node/fc35b67a-3cea-4e3b-bfc7-17018413f4d6.
  $menu_links['main-menu_home-basic:uuid/node/fc35b67a-3cea-4e3b-bfc7-17018413f4d6'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/fc35b67a-3cea-4e3b-bfc7-17018413f4d6',
    'router_path' => 'uuid',
    'link_title' => 'Home Basic',
    'options' => array(
      'identifier' => 'main-menu_home-basic:uuid/node/fc35b67a-3cea-4e3b-bfc7-17018413f4d6',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 0,
    'uuid' => 'fc35b67a-3cea-4e3b-bfc7-17018413f4d6',
    'vuuid' => '67868de8-5e68-4cf9-9f4c-7a88587e12de',
    'parent_identifier' => 'main-menu_home:uuid/node/5ba48b9e-63be-4e62-a816-aa3a95159c8a',
  );
  // Exported menu link: main-menu_home-blog-classic:uuid/node/703a60cd-2aa6-42ae-8ef9-cb207933bf35.
  $menu_links['main-menu_home-blog-classic:uuid/node/703a60cd-2aa6-42ae-8ef9-cb207933bf35'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/703a60cd-2aa6-42ae-8ef9-cb207933bf35',
    'router_path' => 'uuid',
    'link_title' => 'Home Blog Classic',
    'options' => array(
      'identifier' => 'main-menu_home-blog-classic:uuid/node/703a60cd-2aa6-42ae-8ef9-cb207933bf35',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 0,
    'uuid' => '703a60cd-2aa6-42ae-8ef9-cb207933bf35',
    'vuuid' => 'b6a2e6de-8825-49b2-b498-9beb570e82bd',
    'parent_identifier' => 'main-menu_home:uuid/node/5ba48b9e-63be-4e62-a816-aa3a95159c8a',
  );
  // Exported menu link: main-menu_home-business-clean:uuid/node/760f2195-e3fd-4957-ac92-410530f39825.
  $menu_links['main-menu_home-business-clean:uuid/node/760f2195-e3fd-4957-ac92-410530f39825'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/760f2195-e3fd-4957-ac92-410530f39825',
    'router_path' => 'uuid',
    'link_title' => 'Home Business Clean',
    'options' => array(
      'identifier' => 'main-menu_home-business-clean:uuid/node/760f2195-e3fd-4957-ac92-410530f39825',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 0,
    'uuid' => '760f2195-e3fd-4957-ac92-410530f39825',
    'vuuid' => '9cc4c11b-6279-4c5d-8d7d-9fb548feccb2',
    'parent_identifier' => 'main-menu_home:uuid/node/5ba48b9e-63be-4e62-a816-aa3a95159c8a',
  );
  // Exported menu link: main-menu_home-canvas:uuid/node/2bc7e0bd-0597-455f-9730-a058acce07dd.
  $menu_links['main-menu_home-canvas:uuid/node/2bc7e0bd-0597-455f-9730-a058acce07dd'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/2bc7e0bd-0597-455f-9730-a058acce07dd',
    'router_path' => 'uuid',
    'link_title' => 'Home Canvas',
    'options' => array(
      'identifier' => 'main-menu_home-canvas:uuid/node/2bc7e0bd-0597-455f-9730-a058acce07dd',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 0,
    'uuid' => '2bc7e0bd-0597-455f-9730-a058acce07dd',
    'vuuid' => 'a9b8b0cd-2137-43fc-b1be-3d66e5b7fb2a',
    'parent_identifier' => 'main-menu_home:uuid/node/5ba48b9e-63be-4e62-a816-aa3a95159c8a',
  );
  // Exported menu link: main-menu_home-main-demo:uuid/node/c8982be9-90c8-4813-ad2d-87c0934213e4.
  $menu_links['main-menu_home-main-demo:uuid/node/c8982be9-90c8-4813-ad2d-87c0934213e4'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/c8982be9-90c8-4813-ad2d-87c0934213e4',
    'router_path' => 'uuid',
    'link_title' => 'Home Main Demo',
    'options' => array(
      'identifier' => 'main-menu_home-main-demo:uuid/node/c8982be9-90c8-4813-ad2d-87c0934213e4',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 0,
    'uuid' => 'c8982be9-90c8-4813-ad2d-87c0934213e4',
    'vuuid' => '17c4fb10-0c85-4b9c-8139-3b6ac3307485',
    'parent_identifier' => 'main-menu_home:uuid/node/5ba48b9e-63be-4e62-a816-aa3a95159c8a',
  );
  // Exported menu link: main-menu_home:uuid/node/5ba48b9e-63be-4e62-a816-aa3a95159c8a.
  $menu_links['main-menu_home:uuid/node/5ba48b9e-63be-4e62-a816-aa3a95159c8a'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/5ba48b9e-63be-4e62-a816-aa3a95159c8a',
    'router_path' => 'uuid',
    'link_title' => 'Home',
    'options' => array(
      'attributes' => array(
        'title' => '',
      ),
      'identifier' => 'main-menu_home:uuid/node/5ba48b9e-63be-4e62-a816-aa3a95159c8a',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 1,
    'expanded' => 1,
    'weight' => -50,
    'customized' => 0,
    'uuid' => '5ba48b9e-63be-4e62-a816-aa3a95159c8a',
    'vuuid' => '38599502-69a1-479b-95e9-104ec7f51839',
  );
  // Exported menu link: main-menu_homepage-portfolio-1:uuid/node/d880e681-e7a1-494f-b182-f7da873cff88.
  $menu_links['main-menu_homepage-portfolio-1:uuid/node/d880e681-e7a1-494f-b182-f7da873cff88'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/d880e681-e7a1-494f-b182-f7da873cff88',
    'router_path' => 'uuid',
    'link_title' => 'Homepage Portfolio 1',
    'options' => array(
      'attributes' => array(),
      'identifier' => 'main-menu_homepage-portfolio-1:uuid/node/d880e681-e7a1-494f-b182-f7da873cff88',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 0,
    'uuid' => 'd880e681-e7a1-494f-b182-f7da873cff88',
    'vuuid' => '996dddaa-4a0a-4474-89f9-e728d4501721',
    'parent_identifier' => 'main-menu_home:uuid/node/5ba48b9e-63be-4e62-a816-aa3a95159c8a',
  );

  // Translatables
  // Included for use with string extractors like potx.
  t('Home');
  t('Home App Landing Page');
  t('Home Basic');
  t('Home Blog Classic');
  t('Home Business Clean');
  t('Home Canvas');
  t('Home Main Demo');
  t('Homepage Portfolio 1');

  return $menu_links;
}
